### PR TITLE
Redux Bookstore Milestone 1: Setting up initial files.

### PR DESCRIPTION
**Pull request by Abhigyan001**
- Used create-react-app to initialize the project and removed unnecessary assets.
- Added react-redux, prop types, redux using npm.
- Added linter files and removed linter errors.
- Successfully deployed to heroku.

### CODE REVIEW

**Review by uche-inyama — CHANGES_REQUESTED** [review]
## Changes Required

## Hi @Abhigyan001 :wave: 

You meet most of the requirements. However, your deployed application is not coming up.

Here is this image as a reference.

tsee

Please do rectify the issue, and resubmit another form for a review.

### Have a great day :wave: 

#### ``` Uchechukwu Henry Inyama ```

**Comment by Abhigyan001** [comment]
working properly on my end.

**Comment by Abhigyan001** [comment]
Capture

**Comment by shloch** [comment]
## hello

Works for me too. On basis of this, you get a thumbs up


HAPPY CODING

**Pull request merged**
